### ISSUE TITLE
New TAG information 0x3Fh (63 decimal) discovered

### ISSUE THREAD

**Issue by jps1x2** [FluffyKaon/TomTom-ttbin-file-format#4]
Hi,

First of all congratulate you for your work.

i am a programmer and like investigate ttbin file format too.

I have one tomtom multisport watch with version 1.8.25 firmware.

I have discovered what information has the tag 0x3Fh (63 decimal).

In my workouts is always the third TAG beginning from the bottom of the file.

TAG Length: 9
TAG Example1: 3F 04 00 00 00 2E 00 00 00
TAG Example2: 3F 03 00 00 00 24 00 00 00
TAG Example3: 3F 04 00 00 00 30 00 00 00
TAG Example4: 3F 04 00 00 00 30 00 00 00

Info:

First Byte 3F - TAG Code
Second byte: 0x04h Excelent, 0x03h Good, other values i don't have examples
Third, Fourth and fifth byte always 0
Sixth Byte: Heart Rate Recovery (46, 36, 48, 48 decimal values obtained from watch)
seventh, eighth and ninth always 0

I can send you ttbin files with this information if you need it.

Regards

Jorge

**Comment by FluffyKaon** [comment]
Sorry, I can't work on this project anymore. Maybe one of you can fork it and maintain it using the information coming from TomTom?
